FROM ghcr.io/graalvm/native-image-community:25@sha256:0d936f32bb8acb5bc60c41b33e05f064d7a6aaf36b726538296c54949bd4a3c0 AS builder
WORKDIR /workspace/app

RUN microdnf install -y findutils

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY eclipse-style.xml eclipse-style.xml
COPY src src
#COPY api-spec api-spec

RUN chmod +x ./gradlew
RUN ./gradlew :nativeCompile

FROM debian:stable-20240701-slim@sha256:f8bbfa052db81e5b8ac12e4a1d8310a85d1509d4d0d5579148059c0e8b717d4e
WORKDIR /app/

EXPOSE 8080

COPY --from=builder /workspace/app/build/native/nativeCompile/pagopa-posgw-transactions-handler .

ENV OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED=true

ENTRYPOINT ["./pagopa-posgw-transactions-handler"]