FROM ghcr.io/graalvm/native-image-community:25 AS builder
WORKDIR /workspace/app

RUN microdnf install -y findutils

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY eclipse-style.xml eclipse-style.xml
COPY src src
#COPY api-spec api-spec

RUN chmod +x ./gradlew
RUN ./gradlew :nativeCompile

FROM debian:stable-20240701-slim
WORKDIR /app/

EXPOSE 8080

COPY --from=builder /workspace/app/build/native/nativeCompile/pagopa-posgw-transactions-handler .

ENV OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED=true

ENTRYPOINT ["./pagopa-posgw-transactions-handler"]