# version 25-alpine
FROM amazoncorretto@sha256:2ad5f5cf03a3970f2478b130dc28f51b179ce13c58154fe3ec1a6fdeb3b86e3a AS build
WORKDIR /workspace/app

COPY gradlew .
COPY gradle gradle
COPY gradle.lockfile .
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY eclipse-style.xml eclipse-style.xml
COPY src src
COPY api-spec api-spec

RUN chmod +x ./gradlew
RUN ./gradlew build -x test
#remove plain jar, required by native compilations only
RUN rm build/libs/*-plain.jar
RUN cp build/libs/*.jar application.jar
RUN mkdir build/extracted && java -Djarmode=tools -jar application.jar extract --layers --destination build/extracted

# version 25-alpine
FROM amazoncorretto@sha256:2ad5f5cf03a3970f2478b130dc28f51b179ce13c58154fe3ec1a6fdeb3b86e3a

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

WORKDIR /app/

ARG EXTRACTED=/workspace/app/build/extracted

COPY --from=build --chown=user ${EXTRACTED}/dependencies/ ./
RUN true
COPY --from=build --chown=user ${EXTRACTED}/spring-boot-loader/ ./
RUN true
COPY --from=build --chown=user ${EXTRACTED}/snapshot-dependencies/ ./
RUN true
COPY --from=build --chown=user ${EXTRACTED}/application/ ./
RUN true

ENV OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED=true

ENTRYPOINT ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "application.jar"]