#spring.application.name=pagopa-posgw-transactions-handler
application.name=${name}
build.version=${version}
# Logging
logging.level.root=\${ROOT_LOGGING_LEVEL:INFO}
logging.level.it.pagopa=\${APP_LOGGING_LEVEL:INFO}
logging.level.web=\${WEB_LOGGING_LEVEL:INFO}
spring.profiles.active=\${ACTIVE_PROFILE:local}

# Azure Service Bus
azure.servicebus.queues.ecommerce.sync.queue-name=\${SERVICE_BUS_ECOMMERCE_SYNC_QUEUE_NAME}
azure.servicebus.queues.ecommerce.sync.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.queues.ecommerce.sync-retry.queue-name=\${SERVICE_BUS_ECOMMERCE_SYNC_RETRY_QUEUE_NAME}
azure.servicebus.queues.ecommerce.sync-retry.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.queues.gec.sync.queue-name=\${SERVICE_BUS_GEC_SYNC_QUEUE_NAME}
azure.servicebus.queues.gec.sync.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.queues.gec.sync-retry.queue-name=\${SERVICE_BUS_GEC_SYNC_RETRY_QUEUE_NAME}
azure.servicebus.queues.gec.sync-retry.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.queues.session.poll.queue-name=\${SERVICE_BUS_SESSION_POLLING_QUEUE_NAME}
azure.servicebus.queues.session.poll.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.queues.session.expire.queue-name=\${SERVICE_BUS_SESSION_EXPIRE_QUEUE_NAME}
azure.servicebus.queues.session.expire.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}
azure.servicebus.topics.system.telemetry.topic-name=\${SERVICE_BUS_SYSTEM_TELEMETRY_TOPIC_NAME}
azure.servicebus.topics.system.telemetry.connection-string=\${SERVICE_BUS_ECOMMERCE_SYNC_CONNECTION_STRING}