#spring.application.name=pagopa-posgw-transactions-handler
application.name=${name}
build.version=${version}
# Logging
logging.level.root=\${ROOT_LOGGING_LEVEL:INFO}
logging.level.it.pagopa=\${APP_LOGGING_LEVEL:INFO}
logging.level.web=\${WEB_LOGGING_LEVEL:INFO}
spring.profiles.active=\${ACTIVE_PROFILE:local}