#spring.application.name=pagopa-posgw-transactions-handler
application.name=${name}
build.version=${version}
# Logging
logging.level.root=\${ROOT_LOGGING_LEVEL:INFO}
logging.level.it.pagopa=\${APP_LOGGING_LEVEL:INFO}
logging.level.web=\${WEB_LOGGING_LEVEL:INFO}
spring.profiles.active=\${ACTIVE_PROFILE:local}

spring.cloud.azure.servicebus.connection-string=Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
spring.cloud.azure.servicebus.entity-name=posgw.cmd.ecommerce.sync
spring.cloud.azure.servicebus.entity-type=queue