microservice-chart:
  namespace: "posgw"
  nameOverride: ""
  fullnameOverride: "pagopa-posgw-transactions-handler"
  image:
    repository: pagopaditncoreacr.azurecr.io/pagopaposgwtransactionshandler
    tag: "0.0.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "itndev.posgw.internal.dev.platform.pagopa.it"
    path: /pagopa-posgw-transactions-handler/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "posgw-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    ACTIVE_PROFILE: k8s
    ROOT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "off"
    OTEL_SERVICE_NAME: "pagopa-posgw-transactions-handler"
    OTEL_SERVICE_ENVIRONMENT: "dev"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    TEST: test1
  keyvault:
    name: "pagopa-d-itn-posgw-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  azure:
    workloadIdentityClientId: "bc7e1548-f84f-4cb4-aca2-38efd2797fb5"